# Basic info
name: Gubler's Landing
description: This is my site!
author: Erich Gubler
author_email: erichdongubler@gmail.com
url: http://erichdongubler.github.io

# Excludes/includes
exclude: [README.md]
include: ["_pages", "_resources", ".htaccess"]

permalink: pretty
gems:
  - jekyll-redirect-from

# Parsing config
kramdown:
  input: GFM
  hard_wrap: false

# Defaults for the blog content
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
# Pages
  -
    scope:
      type: "pages"
    values:
      layout: "page"
# Posts
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# PT (Portuguese)
  -
    scope:
      type: "pages"
      path: "_pages/pt"
    values:
      lang: "pt"
  -
    scope:
      type: "posts"
      path: "_posts/pt"
    values:
      lang: "pt"